apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: kubelet-restart-engine
  namespace: litmus
spec:
  chaosServiceAccount: litmus-admin
  experiments:
    - name: kubelet-restart
      spec:
        components:
          env:
            - name: TARGET_NODE
              value: "node01"
  annotationCheck: "false"
  engineState: active
  jobCleanUpPolicy: delete

---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: core-dns-engine
  namespace: litmus
spec:
  chaosServiceAccount: litmus-admin
  experiments:
    - name: core-dns
      spec:
        components:
          env:
            - name: TARGET_NODE
              value: "node01"
  annotationCheck: "false"
  engineState: active
  jobCleanUpPolicy: delete

---

apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: docker-restart-engine
  namespace: litmus
spec:
  chaosServiceAccount: litmus-admin
  experiments:
    - name: docker-restart
      spec:
        components:
          env:
            - name: TARGET_NODE
              value: "node01"
  annotationCheck: "false"
  engineState: active
  jobCleanUpPolicy: delete

---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: calico-controller-engine
  namespace: litmus
spec:
  chaosServiceAccount: litmus-admin
  experiments:
    - name: calico-controller
      spec:
        components:
          env:
            - name: TARGET_NODE
              value: "node01"
  annotationCheck: "false"
  engineState: active
  jobCleanUpPolicy: delete

---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: calico-node-kill-engine
  namespace: litmus
spec:
  chaosServiceAccount: litmus-admin
  experiments:
    - name: calico-node-kill-controller
      spec:
        components:
          env:
            - name: TARGET_NODE
              value: "node01"
  annotationCheck: "false"
  engineState: active
  jobCleanUpPolicy: delete
