apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: kubelet-restart-engine
  namespace: litmus
spec:
  chaosServiceAccount: litmus-admin
  experiments:
    - name: kubelet-restart
      spec:
        components:
          env:
            - name: TARGET_NODE
              value: "node01"
    - name: core-dns 
  annotationCheck: "false"
  engineState: active
  jobCleanUpPolicy: delete
