apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: core-dns-engine
  namespace: litmus
spec:
  chaosServiceAccount: litmus-admin
  experiments:
    - name: "core-dns"
  annotationCheck: "false"
  engineState: active
  jobCleanUpPolicy: delete
