apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: core-dns-engine
  namespace: litmus
spec:
  appinfo:
    appns: kube-system
    applabel: k8s-app=kube-dns
    appkind: deployment
  chaosServiceAccount: litmus-admin
  experiments:
    - name: core-dns
      spec:
        components:
          env:
            - name: TARGET_NODE
              value: "node01"
  annotationCheck: "false"
  engineState: active
  jobCleanUpPolicy: delete
