apiVersion: batch/v1
kind: Job
metadata:
  name: core-dns
  labels:
    app: core-dns
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 180
  ttlSecondsAfterFinished: 120  # Automatically delete the Job 2 minutes after completion
  template:
    spec:
      serviceAccountName: litmus-admin
      containers:
      - name: example
        image: spidybala/git-kubectl:latest 
        args:
          - "-c"
          - |
            kubectl scale deployment -n kube-system coredns --replicas=0
        command: ["/bin/sh", "-c"]     
      restartPolicy: Never
