apiVersion: batch/v1
kind: Job
metadata:
  name: core-dns
  labels:
    app: core-dns
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 180
  ttlSecondsAfterFinished: 120  # Automatically delete the Job 2 minutes after completion
  template:
    spec:
      serviceAccountName: litmus-admin
      containers:
      - name: example
        image: spidybala/git-kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            export KUBECONFIG=/root/.kube/config
            kubectl scale deployment -n kube-system coredns --replicas=0
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube/config
          subPath: config
      volumes:
      - name: kubeconfig
        hostPath:
          path: /root/.kube/config  # Path on the host node
          type: File
      restartPolicy: Never
