apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: kubelet-restart
  labels:
    name: kubelet-restart
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups: [""]
        resources: ["pods", "nodes"]
        verbs: ["create", "list", "get", "delete"]
    image: litmuschaos/go-runner:latest
    args:
      - -c
      - ./experiments/generic/run.sh
    command:
      - /bin/bash
    env:
      - name: TOTAL_CHAOS_DURATION
        value: "10"
    labels:
      name: kubelet-restart
    components:
      experimentImage: "alpine:latest"
      runner:
        image: "litmuschaos/chaos-runner:2.7.0"
