apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: calico-controller-engine
  namespace: litmus
spec:
  chaosServiceAccount: litmus-admin
  experiments:
    - name: calico-controller
      spec:
        components:
          env:
            - name: TARGET_NODE
              value: "node01"
  annotationCheck: "false"
  engineState: active
  jobCleanUpPolicy: delete
