apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: kubelet-restart
  namespace: litmus
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups: [""]
        resources: ["pods", "nodes"]
        verbs: ["get", "list", "patch", "delete"]
    image: spidybala/git-kubectl:latest  # Custom image with git and kubectl
    args:
      - "-c"
      - |
        # Clone the Git repository containing the job.yaml
        git clone https://github.com/balarobin/ansiblelitmus /litmus-ansible &&
        
        # Now, execute the job.yaml file to restart the kubelet
        kubectl apply -f /litmus-ansible/utils/kubelet-restart.yaml
        
    command:
      - /bin/bash
    env:
      - name: ANSIBLE_FORCE_COLOR
        value: "true"
    experimentResources:
      - name: job-template
        resource: job.yaml  # You can also specify this job directly if needed
    labels:
      name: kubelet-restart
    scope: Cluster
