apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: kubelet-restart
  namespace: litmus
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups: [""]
        resources: ["pods", "nodes", "jobs"]
        verbs: ["get", "list", "create", "delete"]
    image: spidybala/git-kubectl:latest  # or your custom image with git + kubectl
    command:
      - /bin/sh
    args:
      - -c
      - |
        git clone https://github.com/balarobin/ansiblelitmus /tmp/job &&
        kubectl apply -f /tmp/job/utils/kubelet-restart-job.yaml
    env:
      - name: TOTAL_CHAOS_DURATION
        value: "10"
