apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: kubelet-restart
  labels:
    name: kubelet-restart
spec:
  definition:
    scope: Node
    permissions:
      - apiGroups: [""]
        resources: ["pods", "nodes"]
        verbs: ["create", "list", "get", "delete", "patch"]
    image: litmuschaos/go-runner:latest
    command:
      - /bin/bash
    args:
      - -c
      - |
        set -x # Enable debugging
        echo "Attempting to restart kubelet directly on the node..."
        #  Mount the node's root filesystem.  This is VERY important.
        mount --bind / /hostroot
        #  Use chroot to execute commands in the node's environment.
        chroot /hostroot /bin/bash -c "systemctl stop kubelet"
        echo "Kubelet stop command executed."
        chroot /hostroot /bin/bash -c "systemctl status kubelet" # check the status
        echo "Kubelet status checked."
    env:
      - name: TARGET_NODE
        value: ""
    labels:
      name: kubelet-restart
    components:
      experimentImage: alpine:latest #  alpine
      runner:
        image: "litmuschaos/chaos-runner:2.7.0"
