apiVersion: batch/v1
kind: Job
metadata:
  name: kubelet-restart-job
spec:
  template:
    spec:
      hostPID: true
      nodeName: TARGET_NODE_NAME
      containers:
        - name: kubelet-restart
          image: rockylinux:8
          securityContext:
            privileged: true
          command:
            - /bin/bash
            - -c
            - |
              yum install -y util-linux &&
              nsenter --target 1 --mount --uts --ipc --net --pid systemctl stop kubelet &&
              echo "Kubelet restarted successfully!"
      restartPolicy: Never
