apiVersion: batch/v1
kind: Job
metadata:
  name: kubelet-restart-job
spec:
  template:
    spec:
      hostPID: true
      containers:
        - name: kubelet-restart
          image: rockylinux:8
          command:
            - /bin/bash
            - -c
            - |
              yum install -y util-linux &&
              nsenter --target 1 --mount --uts --ipc --net --pid systemctl restart kubelet
          securityContext:
            privileged: true
      restartPolicy: Never
      nodeName: <your-target-node-name>
