apiVersion: batch/v1
kind: Job
metadata:
  name: kubelet-restart-job
  labels:
    app: kubelet-restart
spec:
  template:
    metadata:
      name: kubelet-restart-job
    spec:
      containers:
        - name: kubelet-restart
          image: busybox
          command:
            - /bin/sh
            - -c
            - "systemctl restart kubelet"
      restartPolicy: Never
