apiVersion: batch/v1
kind: Job
metadata:
  name: kubelet-restart
  labels:
    app: kubelet-restart
spec:
  template:
    spec:
      nodeName: TARGET_NODE
      activeDeadlineSeconds: 180
      restartPolicy: Never
      hostPID: true
      containers:
        - name: kubelet-restart
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache util-linux
              echo "Restarting kubelet..."
              nsenter --mount=/host/proc/1/ns/mnt systemctl stop kubelet
              echo "Kubelet restarted"
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-root
              mountPath: /host
      volumes:
        - name: host-root
          hostPath:
            path: /  # Mounting the root directory of the host
