apiVersion: batch/v1
kind: Job
metadata:
  name: delayed-job
  namespace: litmus
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 180
  ttlSecondsAfterFinished: 120  # Automatically delete the Job 2 minutes after completion
  template:
    spec:
      containers:
      - name: example
        image: spidybala/git-kubectl:latest 
        args:
          - "-c"
          - |
            sleep 180 &&
            kubectl delete job -n litmus kubelet-restart             
        command: ["/bin/sh", "-c"]     
      restartPolicy: Never
